name: Deploy Cloud Function with WIF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: "projects/512488159671/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-actions@new-project-460404.iam.gserviceaccount.com"

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy send_notification \
          --runtime python310 \
          --trigger-topic my-topic1 \
          --entry-point send_notification \
          --source . \
          --region=us-central1 \
          --set-env-vars="username=${{ secrets.EMAIL_USERNAME }},password=${{ secrets.EMAIL_PASSWORD }},sender=${{ secrets.EMAIL_SENDER }},SMTP=${{ secrets.EMAIL_SMTP }},recipients=${{ secrets.EMAIL_RECIPIENTS }}"

